[package]
name = "netcanv"
version = "0.4.0"
authors = ["lqdev <liquidekgaming@gmail.com>"]
edition = "2018"

[workspace]
members = [
   "netcanv-renderer",
   "netcanv-renderer-opengl",
   "netcanv-renderer-skia",
   "netcanv-matchmaker",
   "netcanv-protocol",
   "wasm-test-plugin"
]

[features]
default = ["renderer-opengl"]
renderer-skia = ["netcanv-renderer-skia"]
renderer-opengl = ["netcanv-renderer-opengl"]

[dependencies]

# Wasmer
wasmer = "2.0"

# Common things
anyhow = "1.0.40"
heapless = { version = "0.7.7", default-features = false }

# Windowing and graphics
winit = "0.24.0"
native-dialog = "0.5.5"
image = { version = "0.23.14", default-features = false, features = ["png", "jpeg"] }
webp = { version = "0.2.0", features = ["img"] }
usvg = { version = "0.14.0", default-features = false }
resvg = { version = "0.14.0", default-features = false }
tiny-skia = { version = "0.5.0", default-features = false, features = ["std", "simd"] }

# Networking
serde = { version = "1.0.123", features = ["derive"] }
bincode = "1.3.2"

# Multithreading
nysa = "0.2.2"

# Utilities
directories = "3.0.2"
toml = "0.5.8"

# Clipboard
copypasta = "0.7.1"

# Workspace
netcanv-renderer = { path = "netcanv-renderer" }
netcanv-renderer-skia = { path = "netcanv-renderer-skia", optional = true }
netcanv-renderer-opengl = { path = "netcanv-renderer-opengl", optional = true }
netcanv-protocol = { path = "netcanv-protocol" }

[profile.release]
lto = "fat"
