[package]
name = "netcanv"
version = "0.2.0"
authors = ["lqdev <liquidekgaming@gmail.com>"]
edition = "2018"

[workspace]
members = ["netcanv-matchmaker", "netcanv-protocol"]

[dependencies]
winit = "0.24.0"
skulpin = { version = "0.14.0", features = ["skia-complete", "winit-app", "winit-24"] }
usvg = "0.14.0"
resvg = "0.14.0"
tiny-skia = "0.5.0"
serde = { version = "1.0.123", features = ["derive"] }
bincode = "1.3.2"
crossbeam-channel = "0.4.4"
anyhow = "1.0.40"
image = "0.23.14"
native-dialog = "0.5.5"
toml = "0.5.8"
directories = "3.0.2"
webp = { version = "0.2.0", features = ["img"] }

clap = "2.33.3"

serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }

netcanv-protocol = { path = "netcanv-protocol" }

[profile.release]
lto = true
