name: Build AppImage

on:
  push:
    branches: [release-ci]
  pull_request:
    branches: [release-ci]  
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-appimage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Compile application
      run: cargo build --release
    - name: Compile matchmaker
      working-directory: netcanv-matchmaker
      run: cargo build --release

    - name: Build AppImages
      run: bash build/appimages.sh

    - name: Release
      uses: AButler/upload-release-assets@v2.0
      if: github.event_name == 'release' && github.event.action == 'created'
      with:
        files: 'appimages/NetCanv*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
