name: Generate AppImages

on:
  push:
    branches: [ wallhackd ]
  pull_request:
    branches: [ wallhackd ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate AppImages
      run: cd appimage ; ./generate.sh
    - name: Upload AppImages as Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: AppImages
        path: appimage/out/